services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: postgre
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:8-alpine
    container_name: redis
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # User Service
  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile.prod
    container_name: user-service
    restart: unless-stopped
    environment:
      - NODE_ENV= production
      - PORT=8001
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=user_service
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: sh -c "npm run prisma:setup:with-seed && npm start"

  # Audio Service
  audio-service:
    build:
      context: ./backend/audio-service
      dockerfile: Dockerfile.prod
    container_name: audio-service
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8002
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=audio_service
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - UPLOAD_DIR=/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - uploads_data:/app/uploads
    command: sh -c "npm run prisma:setup && npm start"

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - NEXT_PUBLIC_USER_SERVICE_URL=/api/users
        - NEXT_PUBLIC_AUTH_SERVICE_URL=/api/auth
        - NEXT_PUBLIC_AUDIO_SERVICE_URL=/api/audio
        - NEXT_PUBLIC_AUDIO_FILE_URL=/uploads/audio
    container_name: frontend
    restart: unless-stopped
    command: npm start

  # Caddy Reverse Proxy
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - uploads_data:/app/uploads
      - caddy_data:/data
      - caddy_config:/config

volumes:
  postgres_data:
  redis_data:
  uploads_data:
  caddy_data:
  caddy_config:
